import type { DeploymentActivationExecutorResult } from "./deployment-activation-executor-types";
import type {
  DeploymentExecutionStepCompletionStatus,
  DeploymentExecutionStepNextStartStatus,
  DeploymentExecutionStepOrchestratorContext,
  DeploymentExecutionStepOrchestratorItem,
  DeploymentExecutionStepOrchestratorStageResult,
  DeploymentExecutionStepProgressionStatus,
} from "./deployment-execution-step-orchestrator-types";

export interface DeploymentExecutionStepRunnerInput {
  context: DeploymentExecutionStepOrchestratorContext;
  item: DeploymentExecutionStepOrchestratorItem;
}
export interface DeploymentExecutionStepItemCompletionRunnerInput extends DeploymentExecutionStepRunnerInput { entityExecution: DeploymentActivationExecutorResult; }
export interface DeploymentExecutionStepDependencyProgressionRunnerInput extends DeploymentExecutionStepItemCompletionRunnerInput { itemCompletion: DeploymentExecutionStepOrchestratorStageResult<DeploymentExecutionStepCompletionStatus>; }
export interface DeploymentExecutionStepNextItemStartRunnerInput extends DeploymentExecutionStepDependencyProgressionRunnerInput { dependencyProgression: DeploymentExecutionStepOrchestratorStageResult<DeploymentExecutionStepProgressionStatus>; }

export interface DeploymentExecutionStepEntityRunner {
  readonly runnerId: string;
  executeEntity(input: DeploymentExecutionStepRunnerInput): Promise<DeploymentActivationExecutorResult> | DeploymentActivationExecutorResult;
}

export interface DeploymentExecutionStepItemCompletionRunner {
  readonly runnerId: string;
  completeItem(input: DeploymentExecutionStepItemCompletionRunnerInput): Promise<DeploymentExecutionStepOrchestratorStageResult<DeploymentExecutionStepCompletionStatus>> | DeploymentExecutionStepOrchestratorStageResult<DeploymentExecutionStepCompletionStatus>;
}

export interface DeploymentExecutionStepDependencyProgressionRunner {
  readonly runnerId: string;
  progressDependencies(input: DeploymentExecutionStepDependencyProgressionRunnerInput): Promise<DeploymentExecutionStepOrchestratorStageResult<DeploymentExecutionStepProgressionStatus>> | DeploymentExecutionStepOrchestratorStageResult<DeploymentExecutionStepProgressionStatus>;
}

export interface DeploymentExecutionStepNextItemStartRunner {
  readonly runnerId: string;
  startNextItem(input: DeploymentExecutionStepNextItemStartRunnerInput): Promise<DeploymentExecutionStepOrchestratorStageResult<DeploymentExecutionStepNextStartStatus>> | DeploymentExecutionStepOrchestratorStageResult<DeploymentExecutionStepNextStartStatus>;
}

export interface DeploymentExecutionStepOrchestratorRunners {
  entityExecution: DeploymentExecutionStepEntityRunner;
  itemCompletion: DeploymentExecutionStepItemCompletionRunner;
  dependencyProgression: DeploymentExecutionStepDependencyProgressionRunner;
  nextItemStart: DeploymentExecutionStepNextItemStartRunner;
}
